FROM node:18 as build

WORKDIR /usr/src/app

COPY package.json .
RUN npm install
COPY . .

FROM node:18-slim
RUN apt update && apt install libssl-dev dumb-init -y --no-install-recommends
WORKDIR /usr/src/app

# Add build arguments and environment variables
ARG PVK_ENCRYPTION_SALT
ARG NODE_ENV
ARG NIXPACKS_NODE_VERSION
ARG ADMIN_JWT_SECRET
ARG API_TOKEN_SALT
ARG APP_KEYS
ARG APP_PRIVATE_KEY
ARG APP_PUBLIC_KEY
ARG HOST
ARG PORT
ARG TRANSFER_TOKEN_SALT
ARG PGDATABASE
ARG PGHOST
ARG PGPASSWORD
ARG PGPORT
ARG PGUSER
ARG URL
ARG WS_API_ENDPOINT
ARG CHAIN_ID

ENV PVK_ENCRYPTION_SALT=$PVK_ENCRYPTION_SALT
ENV NODE_ENV=$NODE_ENV
ENV NIXPACKS_NODE_VERSION=$NIXPACKS_NODE_VERSION
ENV ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
ENV API_TOKEN_SALT=$API_TOKEN_SALT
ENV APP_KEYS=$APP_KEYS
ENV APP_PRIVATE_KEY=$APP_PRIVATE_KEY
ENV APP_PUBLIC_KEY=$APP_PUBLIC_KEY
ENV HOST=$HOST
ENV PORT=$PORT
ENV TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT
ENV PGDATABASE=$PGDATABASE
ENV PGHOST=$PGHOST
ENV PGPASSWORD=$PGPASSWORD
ENV PGPORT=$PGPORT
ENV PGUSER=$PGUSER
ENV URL=$URL
ENV WS_API_ENDPOINT=$WS_API_ENDPOINT
ENV CHAIN_ID=$CHAIN_ID

COPY --chown=node:node --from=build /usr/src/app/package.json .
COPY --chown=node:node --from=build /usr/src/app/package-lock.json .
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules


# Build the application
RUN npm run build

EXPOSE 1337

# Run the application
ENTRYPOINT ["strapi", "start"]